### ISSUE TITLE
Feature Proposal: via_cloudformation

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [awslabs/aws-iam-generator#12]
Hey,

# Current Situation

We often have the situation, that we want to allow a Role to do certain things only via cloudformation. This is done  this way:

```yaml
policies:
  cf-deployment:
    description: Allow to pass security-deployment to cloudformation
    policy_file: management-cloudformation.j2
    template_vars:
      cfrole: role-deployment
      cfaccount: 1234567890
    in_accounts:
    - account

roles:
  role:
    trusts:
      - SAMLIDP
    managed_policies:
      - cf-deployment
    in_accounts:
      - account

  role-deployment:
    trusts:
      - cloudformation.amazonaws.com
    managed_policies:
      - <list-of-managed-polices>
    in_accounts:
      - account
```

with `management-cloudformation.j2` looking like this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PassRoleToCloudFormation",
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": "arn:aws:iam::{{ template_vars.cfaccount }}:role/{{ template_vars.cfrole }}"
        }
    ]
}
```

Since we have this pattern relatively often we are looking for a simplification.

# Feature Proposal

Add an option to the role to add certain policy only via cloduformation.

So the a role could be written like this:

```yaml
roles:
  role:
    trusts:
      - SAMLIDP
    managed_policies:
      - cf-deployment
    policies_via_cloudformation:
      - <list-of-policies>
    cloudformation_role_name: <optional-cf-role-name>
    in_accounts:
      - account
```

This would result in the following:

1. An additional Role with name in `cloudformation_role_name` and trust `cloudformation.amazonaws.com` is created and the policies under `policies_via_cloudformation` are added. If `cloudformation_role_name` is not set, the role is named `role-cloudformation`
2. The role `role` is created and an additonal inline policy, which allows `iam:PassRole` with the role  `cloudformation_role_name` is added.

What do you think? Would you accept a PR if I would create one?

Thanks!
