### ISSUE TITLE
Support for Direct Federation

### ISSUE THREAD

**Issue by nhawkins04** [awslabs/aws-iam-generator#14]
This configuration works great for a hub-and-spoke method with a central identity account! It would be nice to also have support for direct federation where each account is directly federated. Right now if I try to do this, I get an error if a parent_account is not specified. 

Would be nice if we could declare the configuration like this and it would have the role in each account have a trust relationship to a SAML provider configured in the same account:

```yaml
accounts:
  account1:
    id: 000000000000
    saml_provider: OktaIDP
  account2:
    id: 000000000000
    saml_provider: OktaIDP
roles:
  ReadOnly:
    trusts:
      - OktaIDP
    managed_policies:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
    in_accounts:
      - all
```

I am basing this on some of the new ways we can integrate Okta without the central identity account method: https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Amazon-Web-Service#scenarioB
