### ISSUE TITLE
How do I pass account IDs to Jinja templates?

### ISSUE THREAD

**Issue by Marakai** [awslabs/aws-iam-generator#23]
I am trying to specify a list of roles into a policy Resource list, however with

```
{% for account_name in config.accounts %}
  - "arn:aws:iam::{{ account_name }}:role/MyRole"
{% endfor %}
```

I only end up with the friendly names - which match neither ID not the account alias (the latter being too long and unwieldy and NOT "friendly").

Staring at the source code, it doesn't seem the `accounts` dictionary makes the IDs available to Jinja templates? Despite there being a function that maps the friendly names to IDs.

I've tried various combinations of `{{ account_name.id }}` and such, but to no avail.

The documentation makes no mention either. Is this currently not possible?

**Comment by nhawkins04** [comment]
Hi @Marakai - after a bit of exploration and curiosity, I was able to make this work. I built out the following sample j2 policy document to demonstrate the capabilities:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "testroleloop",
		  	"Action": [ 
                "iam:Delete*"
            ],
		  	"Effect": "Deny",
		  	"Resource": [
                {% for account_name in config.accounts %}
                    {%if loop.last%}
                        "arn:aws::{{config.accounts[account_name]['id']}}:role/MyRole"
                    {%else%}
                        "arn:aws::{{config.accounts[account_name]['id']}}:role/MyRole",
                    {%endif%}
                {% endfor %}
              ]
		}
	 ]
}
```

I tested this against the current version of iam generator with the following config.yaml (I used the provided config-complex.yaml as a starting point)
```yaml
global:
  names:
    policies: true
    roles: True
    users: True
    groups: True
  template_outputs: enabled

accounts:
  central:
    id: 123456678910
    parent: true
    saml_provider: ProdADFS
  dev1:
    id: 109876543210
  dev2:
    id: 309876543210
  prod:
    id: 209876543210
policies:
  testpolicy:
    description: testpolicy
    policy_file: testpolicy.j2
    in_accounts:
      - dev*

```

These were helpful in the process:
- https://stackoverflow.com/questions/27208891/jinja2-dictonary-lookup-using-a-variable-key
- https://groups.google.com/forum/#!topic/ansible-project/TYbORkOM6Dw

Let me know if this works! 

-Nick
