### ISSUE TITLE
trusts attribute should also allow users and roles

### ISSUE THREAD

**Issue by justjulian** [awslabs/aws-iam-generator#3]
In roles, the `trusts `attribute does not support all supported types, like roles and users, see: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html

For example, when specifying a user as trusted principal, the aws-iam-generator outputs
`ValueError: Unable to find account named 'voyager-jenkins' in the accounts:  section of the config.yaml`

Added supported for this would be highly appreciated.

**Comment by apmclean** [comment]
I agree the Role trust generation is quite rudimentary.  I was thinking of allowing use of a Jinja template as the trust document which would be generated using variabilization from the config.yaml.

Thoughts on that approach?

**Comment by justjulian** [comment]
Using another set of Jinja templates for the trust relations would give the user the most freedom but might make the usability unnecessary complex. Trust relations are usually quite simple and static and not like policies (where Jinja templates absolutely are the perfect fit!).

Looking at the link I posted there are the following types:
* Specific AWS accounts --> already working
* Individual IAM user or users --> [1]
* Federated users --> already working (for SAML identity providers)
* IAM role --> [1]
* Specific assumed-role user --> [2]
* AWS service --> already working
* Everyone (anonymous users) --> [2]

[1] I would probably really "just" extend the current logic that allows to reference existing objects within the config.yaml but [2] also give the option to enter ARNs (this should support referencing the AWS account ID)

I haven't had the chance to look at your code yet to see if that's actually feasible to implement like this. Personally, I would be also happy with your Jinja approach but since you asked, I think in terms of usability the described approach would be quite charming and avoids the maintenance of additional Jinja templates.

**Comment by apmclean** [comment]
Ok makes sense.  Where I was thinking of Jinja was when you get into conditionals like MFA present, time-of-day etc which are difficult to model otherwise.

Since no one has asked for those yet, I'll take a stab at whitelisting other principal types with some lose validation of ARN the various ARN structures.  Should be a fairly simple thing!

**Comment by apmclean** [comment]
Should be sorted!  Thanks!

**Comment by justjulian** [comment]
Wow, super fast, thanks! And yes, you are right, I did not think about conditionals. At this point Jinja templates make more sense.
I got another issue with the generated cf template when I try to create a stack during role creation:
`Invalid principal in policy: "AWS":"arn:aws:iam::xxxxxxxxxxxx:user/myuser"`
The user myuser does not exist at that time, it is being created at the same time as the role, hence the principal is not valid yet. I think here the generated cf template needs to use a Ref() to the user or am I missing something?

**Comment by justjulian** [comment]
Just referencing the user name of a user that is created by the same config is not supported, correct, just the ARN of the user works? See the following example (without the policies). `test-jenkins` cannot directly be used in `trusts`:
```
roles:
  test-ci:
    trusts:
      - test-jenkins
    managed_policies:
      - test-ci
    in_accounts:
      - iat

groups:
  ci:
    managed_policies:
      - assume-test-ci
    in_accounts:
      - iat

users:
  test-jenkins:
    groups:
      - ci
    in_accounts:
      - iat
```

So would you recommend to create the users by a separate cf template and use the ARNs in the config?

**Comment by apmclean** [comment]
Ah, I see what you're getting at!  Let me see if CFN will support having a Ref in the policy that generates the ARN.  If that works then I'll add some code to see if the trust section is a user/role and insert a ref() accordingly.

**Comment by apmclean** [comment]
Give it a shot now!

**Comment by justjulian** [comment]
Works like a charm, thanks!

**Comment by justjulian** [comment]
Hi, I just discovered some issues with the saml provider and users.

1. SAML provider was configured like in your config example:
```
global:
  names:
    policies: True
    roles: True
    users: True
    groups: True
  template_outputs: disabled

accounts:
  central:
    id: 111111111111
    parent: True
  iat:
    id: 111111111112
    saml_provider: SAMLIDP1
  prod:
    id: 111111111113
    saml_provider: SAMLIDP2

policies:
  test-ci:
    description: compute-ec2-lrw
    policy_file: compute-ec2-lrw.j2
    template_vars:
      team: test
    in_accounts:
      - iat

roles:
  test-ci:
    trusts:
      - SAMLIPD1
    managed_policies:
      - test-ci
    in_accounts:
      - iat
```
Output is:
```
Traceback (most recent call last):
  File "iam_template_build.py", line 555, in <module>
    c.config["global"]["names"]["roles"]
  File "iam_template_build.py", line 367, in add_role
    "AssumeRolePolicyDocument": build_role_trust(c, model['trusts']),
  File "iam_template_build.py", line 152, in build_role_trust
    trust
ValueError: Trust name 'SAMLIDP1' in the config.yaml does not appear to be valid.  Confirm it is a valid AWS Principal ARN / AWS Service Principal or an Account Name / SAML Provider contained in the config.yaml

Traceback (most recent call last):
  File "./build.py", line 39, in <module>
    run_sub_build("iam_template_build.py", "bin")
  File "./build.py", line 37, in run_sub_build
    raise RuntimeError("Sub build script failed")
RuntimeError: Sub build script failed
```

2. Then I added a user to the example above:
```
...

users:
  test-jenkins:
    in_accounts:
      - iat
```

Output is:
```
Traceback (most recent call last):
  File "iam_template_build.py", line 555, in <module>
    c.config["global"]["names"]["roles"]
  File "iam_template_build.py", line 367, in add_role
    "AssumeRolePolicyDocument": build_role_trust(c, model['trusts']),
  File "iam_template_build.py", line 118, in build_role_trust
    elif c.is_local_user(trust):
  File "/home/julian/lso/aws-iam-generator/bin/lib/config_helper.py", line 144, in is_local_user
    for user in self.config['users']:
KeyError: 'users'

Traceback (most recent call last):
  File "./build.py", line 39, in <module>
    run_sub_build("iam_template_build.py", "bin")
  File "./build.py", line 37, in run_sub_build
    raise RuntimeError("Sub build script failed")
RuntimeError: Sub build script failed
```

Any ideas here?

**Comment by justjulian** [comment]
This example above also works for me, but it is missing the roles section:
```
roles:
  test-ci:
    trusts:
      - SAMLIPD1
    managed_policies:
      - test-ci
    in_accounts:
      - iat
```
Now this leads to the error mentioned above. If I change the trust to `parent `it works again and then I can even delete the dummy user and it still works.
